import React from "react";
import Head from "next/head";
import styles from "../../styles/Layout.module.scss";
import Nav from "./Nav";

const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.body}>
        <Nav />
        {children}
      </div>
    </>
  );
};

export default Layout;
